name: Android camera mds


on:
  push:
    branches:
      - '!release-branch'
      - release-1*
      - master
      - 1.*
      - develop

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android camera mds
        run: |
          cd MockRegSBI
          chmod +x gradlew
          ./gradlew assembleDebug
          ls app\build\outputs\apk\debug
          find -name '*.apk'
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk-output
          path: ./MockRegSBI/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 5
